theme: jekyll-theme-architect
title: Text Mining Unit
description: Lectures and labs for master students of Data Mining

             Department of Computer Science and Engineering of the University of Bologna
             
