theme: jekyll-theme-architect
title: Text Mining Unit
subtitle: Lectures & labs for students of Data Mining
description: 
             Department of Computer Science and Engineering<br>
             University of Bologna
             
