github:
  is_project_page: false
theme: jekyll-theme-architect
title: Text Mining
description: Prof. Gianluca Moro<br>
             Lectures & labs for master students<br> 
             of Data Mining - University of Bologna<br>
             Dept. Computer Science and Engineering<br>
             
             
