github:
  is_project_page: false
theme: jekyll-theme-architect
title: Text Mining
description: Proff. Gianluca Moro and Nicola Piscaglia<br>
             Lectures & labs for Master in Data Science<br> 
             of The Bologna Business School<br>
           
             
             
