github:
  is_project_page: false
theme: jekyll-theme-architect
title: Text Mining
description: Prof. Gianluca Moro and Dr. Eng. Nicola Piscaglia<br>
             Lectures & labs for the Master in Data Science<br> 
             of The Bologna Business School<br>
           
             
             
