theme: jekyll-theme-architect
title: Text Mining Unit
description: Lectures & labs for master students<br> 
             Subject: Data Mining<br>
             Dept: Computer Science and Engineering<br>
             University of Bologna
             
