theme: jekyll-theme-architect
title: Text Mining Unit
description: Lectures & labs for master students<br> 
             Data Mining - University of Bologna<br>
             Dept. Computer Science and Engineering<br>
             
             
